TITLE = "RuToPy RL"
FONT = "fonts/16x16_sm_ascii.png, size=16x16, codepage=437"

RAW_FILES = '/raws'
SCREEN_WIDTH = 80
SCREEN_HEIGHT = 50

DEFAULT_LANGUAGE = 'en'
FPS = 100

MAP_WIDTH = 80
MAP_HEIGHT = 43
MAP_COUNT = MAP_HEIGHT * MAP_WIDTH

UI_STATS_INFO_LINE = 43
UI_LOG_FIRST_LINE = 44

MAX_DEPTH = 6
MAX_ROOMS = 30
MIN_SIZE = 6
MAX_SIZE = 10

MAX_MONSTERS_ROOM = 3
MAX_ITEMS_ROOM = 2

DEFAULT_VISIBILITY = 10
DEFAULT_HIT_POINTS = 10
DEFAULT_MONSTER_HIT_POINTS = 8
DEFAULT_MANA_POINTS = 4
DEFAULT_NO_SKILL_VALUE = -4
DEFAULT_MONSTER_BODY_ATTRIBUTE = 2
DEFAULT_MONSTER_MIGHT_ATTRIBUTE = 3
DEFAULT_MONSTER_QUICKNESS_ATTRIBUTE = 2
DEFAULT_MONSTER_WITS_ATTRIBUTE = 3
DEFAULT_PLAYER_BODY_ATTRIBUTE = 4
DEFAULT_PLAYER_MIGHT_ATTRIBUTE = 4
DEFAULT_PLAYER_QUICKNESS_ATTRIBUTE = 4
DEFAULT_PLAYER_WITS_ATTRIBUTE = 4
DEFAULT_MIN_DMG = 1
DEFAULT_MAX_DMG = 3

COLOR_PLAYER_INFO_OK = 'lighter blue'
COLOR_PLAYER_INFO_NOT = 'light orange'
COLOR_MAJOR_INFO = 'orange'
COLOR_DEADLY_INFO = 'red'
COLOR_SYS_MSG = 'yellow'

LOW_RADIUS = 3
MEDIUM_RADIUS = 5
HIGH_RADIUS = 7
HUGE_RADIUS = 9



