TITLE="RuToPy RL"
FONT="fonts/16x16_sm_ascii.png, size=16x16, codepage=437"


SCREEN_WIDTH=80
SCREEN_HEIGHT=50

MAP_WIDTH=80
MAP_HEIGHT=43
MAP_COUNT= MAP_HEIGHT * MAP_WIDTH

UI_STATS =43
UI_LOG_FIRST_LINE=44

MAX_ROOMS = 30
MIN_SIZE = 6
MAX_SIZE = 10

MAX_MONSTERS_ROOM = 3
MAX_ITEMS_ROOM = 2

DEFAULT_VISIBILITY = 10

COLOR_PLAYER_INFO_OK = 'lighter blue'
COLOR_PLAYER_INFO_NOT = 'light orange'
COLOR_MAJOR_INFO = 'orange'
COLOR_DEADLY_INFO = 'red'
COLOR_SYS_MSG = 'yellow'

PRECISE_MOUSE = True
